env:
  es2021: true
  node: true
  jest: true
extends:
  - google
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
  - prettier
rules:
  linebreak-style:
    - 0
  require-jsdoc:
    - 0
  camelcase:
    - 0
  new-cap:
    - 0
